# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smart_month}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Derek Perez", "Jonathan Silverman"]
  s.date = %q{2010-01-06}
  s.description = %q{You can use SmartMonth to: 
- Determine the first tuesday of any month in any year. 
- Determine all of the fridays of any month in any year. 
- Iterate through all the days of a month. 
- Determine how many days of the month there are. 
- Determine the first and last days of the month. 
- And other fun date/month related things!}
  s.email = %q{derek@derekperez.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/month.rb",
     "lib/smart_month.rb",
     "lib/smart_month/calculations.rb",
     "lib/smart_month/collection.rb",
     "lib/smart_month/extensions/date.rb",
     "lib/smart_month/magic.rb",
     "lib/smart_month/math.rb",
     "lib/smart_month/rulesets.rb",
     "lib/smart_month/util.rb",
     "rdoc/classes/Date.html",
     "rdoc/classes/Month.html",
     "rdoc/classes/SmartMonth.html",
     "rdoc/classes/SmartMonth/Calculations.html",
     "rdoc/classes/SmartMonth/Collection.html",
     "rdoc/classes/SmartMonth/Magic.html",
     "rdoc/classes/SmartMonth/Magic/MonthFactory.html",
     "rdoc/classes/SmartMonth/Math.html",
     "rdoc/classes/SmartMonth/Rulesets.html",
     "rdoc/classes/SmartMonth/Util.html",
     "rdoc/classes/Time.html",
     "rdoc/created.rid",
     "rdoc/files/README.html",
     "rdoc/files/lib/month_rb.html",
     "rdoc/files/lib/smart_month/calculations_rb.html",
     "rdoc/files/lib/smart_month/collection_rb.html",
     "rdoc/files/lib/smart_month/extensions/date_rb.html",
     "rdoc/files/lib/smart_month/magic_rb.html",
     "rdoc/files/lib/smart_month/math_rb.html",
     "rdoc/files/lib/smart_month/rulesets_rb.html",
     "rdoc/files/lib/smart_month/util_rb.html",
     "rdoc/files/lib/smart_month_rb.html",
     "rdoc/fr_class_index.html",
     "rdoc/fr_file_index.html",
     "rdoc/fr_method_index.html",
     "rdoc/index.html",
     "rdoc/rdoc-style.css",
     "test/spec/date/accessor_spec.rb",
     "test/spec/date/add_month_spec.rb",
     "test/spec/date/add_spec.rb",
     "test/spec/date/boat_spec.rb",
     "test/spec/date/civil_spec.rb",
     "test/spec/date/commercial_spec.rb",
     "test/spec/date/constants_spec.rb",
     "test/spec/date/conversions_spec.rb",
     "test/spec/date/downto_spec.rb",
     "test/spec/date/eql_spec.rb",
     "test/spec/date/gregorian_spec.rb",
     "test/spec/date/hash_spec.rb",
     "test/spec/date/infinity_spec.rb",
     "test/spec/date/julian_spec.rb",
     "test/spec/date/minus_month_spec.rb",
     "test/spec/date/minus_spec.rb",
     "test/spec/date/new_spec.rb",
     "test/spec/date/neww_spec.rb",
     "test/spec/date/ordinal_spec.rb",
     "test/spec/date/parse_spec.rb",
     "test/spec/date/relationship_spec.rb",
     "test/spec/date/shared/civil.rb",
     "test/spec/date/shared/commercial.rb",
     "test/spec/date/shared/parse.rb",
     "test/spec/date/shared/parse_eu.rb",
     "test/spec/date/shared/parse_us.rb",
     "test/spec/date/step_spec.rb",
     "test/spec/date/strftime_spec.rb",
     "test/spec/date/strptime_spec.rb",
     "test/spec/date/upto_spec.rb",
     "test/spec/parsedate/parsedate.rb",
     "test/spec/time/httpdate_spec.rb",
     "test/spec/time/iso8601_spec.rb",
     "test/spec/time/rfc2822_spec.rb",
     "test/spec/time/rfc822_spec.rb",
     "test/spec/time/shared/rfc2822.rb",
     "test/spec/time/shared/xmlschema.rb",
     "test/spec/time/xmlschema_spec.rb",
     "test/spec_helper.rb",
     "test/test_helper.rb",
     "test/unit/calculations_test.rb",
     "test/unit/collection_test.rb",
     "test/unit/magic_test.rb",
     "test/unit/math_test.rb",
     "test/unit/rulesets_test.rb",
     "test/unit/samples/test_ruleset.yml",
     "test/unit/util_test.rb"
  ]
  s.homepage = %q{http://github.com/perezd/smart_month}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{SmartMonth is a "bodysnatcher" plugin that takes boring Date month fixnums and replaces them with a rich toolkit of functionality.}
  s.test_files = [
    "test/test_helper.rb",
     "test/spec/date/strftime_spec.rb",
     "test/spec/date/ordinal_spec.rb",
     "test/spec/date/step_spec.rb",
     "test/spec/date/hash_spec.rb",
     "test/spec/date/new_spec.rb",
     "test/spec/date/relationship_spec.rb",
     "test/spec/date/julian_spec.rb",
     "test/spec/date/shared/parse.rb",
     "test/spec/date/shared/civil.rb",
     "test/spec/date/shared/parse_eu.rb",
     "test/spec/date/shared/parse_us.rb",
     "test/spec/date/shared/commercial.rb",
     "test/spec/date/strptime_spec.rb",
     "test/spec/date/neww_spec.rb",
     "test/spec/date/add_month_spec.rb",
     "test/spec/date/add_spec.rb",
     "test/spec/date/minus_spec.rb",
     "test/spec/date/civil_spec.rb",
     "test/spec/date/minus_month_spec.rb",
     "test/spec/date/commercial_spec.rb",
     "test/spec/date/parse_spec.rb",
     "test/spec/date/gregorian_spec.rb",
     "test/spec/date/downto_spec.rb",
     "test/spec/date/accessor_spec.rb",
     "test/spec/date/upto_spec.rb",
     "test/spec/date/infinity_spec.rb",
     "test/spec/date/boat_spec.rb",
     "test/spec/date/eql_spec.rb",
     "test/spec/date/constants_spec.rb",
     "test/spec/date/conversions_spec.rb",
     "test/spec/parsedate/parsedate.rb",
     "test/spec/time/shared/rfc2822.rb",
     "test/spec/time/shared/xmlschema.rb",
     "test/spec/time/httpdate_spec.rb",
     "test/spec/time/rfc2822_spec.rb",
     "test/spec/time/iso8601_spec.rb",
     "test/spec/time/xmlschema_spec.rb",
     "test/spec/time/rfc822_spec.rb",
     "test/unit/util_test.rb",
     "test/unit/calculations_test.rb",
     "test/unit/collection_test.rb",
     "test/unit/math_test.rb",
     "test/unit/rulesets_test.rb",
     "test/unit/magic_test.rb",
     "test/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

